version: '3.7'
services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: slachroot
      MYSQL_DATABASE: greenit
      MYSQL_USER: slach
      MYSQL_PASSWORD: slach
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    build: './docker/php'
    ports: ['9000:9000']
    volumes: ['./app/:/var/www/app:cached']
    depends_on:
      - database
  nginx:
    container_name: nginx
    build: './docker/nginx'
    ports: ['80:80']
    volumes: ['./app/:/var/www/app:cached']
    depends_on:
      - php
      - database